# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-10 04:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frog', '0003_auto_20160809_2054'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='like_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='video',
            name='like_count',
            field=models.IntegerField(default=0),
        ),
    ]
