# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-24 02:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frog', '0004_auto_20160809_2117'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='poster',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=b'%Y/%m/%d'),
        ),
    ]
