# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-25 06:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frog', '0005_video_poster'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='framerate',
            field=models.IntegerField(default=24),
        ),
    ]
