# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-05 06:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frog', '0006_video_framerate'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='custom_thumbnail',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=b'%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='video',
            name='custom_thumbnail',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=b'%Y/%m/%d'),
        ),
    ]
