# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-09 05:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('frog', '0007_auto_20161004_2333'),
    ]

    operations = [
        migrations.CreateModel(
            name='GallerySubscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.SmallIntegerField(default=0)),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frog.Gallery')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='rssstorage',
            name='gallery',
        ),
        migrations.AlterField(
            model_name='userpref',
            name='data',
            field=models.TextField(default=b'{"emailLikes": true, "thumbnailPadding": 0, "tileCount": 9, "emailComments": true, "backgroundColor": "#000000", "semiTransparent": false}'),
        ),
        migrations.DeleteModel(
            name='RSSStorage',
        ),
    ]
