# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-08 05:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frog', '0008_auto_20170208_2107'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReleaseNotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='userpref',
            name='data',
            field=models.TextField(default=b'{"tileCount": 9, "orderby": "created", "emailLikes": true, "emailComments": true, "showTags": false, "backgroundColor": "#000000", "semiTransparent": false, "thumbnailPadding": 0}'),
        ),
    ]
