# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-10 18:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frog', '0010_remove_like_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='duration',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='userpref',
            name='data',
            field=models.TextField(default=b'{"thumbnailPadding": 0, "slideshowDuration": 5, "emailComments": true, "semiTransparent": false, "slideshowRandomize": true, "orderby": "created", "emailLikes": true, "slideshowPlayVideo": true, "tileCount": 9, "showTags": false, "backgroundColor": "#000000"}'),
        ),
    ]
