# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-06-07 05:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('frog', '0011_auto_20171210_1008'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('thumbnail', models.ImageField(blank=True, max_length=255, null=True, upload_to='%Y/%m/%d')),
                ('custom_thumbnail', models.ImageField(blank=True, max_length=255, null=True, upload_to='%Y/%m/%d')),
                ('width', models.IntegerField(default=0)),
                ('height', models.IntegerField(default=0)),
                ('foreign_path', models.TextField(blank=True)),
                ('unique_id', models.CharField(blank=True, max_length=255)),
                ('guid', models.CharField(blank=True, max_length=16)),
                ('deleted', models.BooleanField(default=False)),
                ('hash', models.CharField(blank=True, max_length=40)),
                ('comment_count', models.IntegerField(default=0)),
                ('like_count', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True, null=True)),
                ('hidden', models.BooleanField(default=False)),
                ('view_count', models.IntegerField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(blank=True, to='frog.Tag')),
            ],
            options={
                'ordering': ['-created', '-id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GroupChild',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.SmallIntegerField(default=0)),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frog.Group')),
            ],
            options={
                'ordering': ('index',),
            },
        ),
        migrations.CreateModel(
            name='Marmoset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('thumbnail', models.ImageField(blank=True, max_length=255, null=True, upload_to='%Y/%m/%d')),
                ('custom_thumbnail', models.ImageField(blank=True, max_length=255, null=True, upload_to='%Y/%m/%d')),
                ('width', models.IntegerField(default=0)),
                ('height', models.IntegerField(default=0)),
                ('foreign_path', models.TextField(blank=True)),
                ('unique_id', models.CharField(blank=True, max_length=255)),
                ('guid', models.CharField(blank=True, max_length=16)),
                ('deleted', models.BooleanField(default=False)),
                ('hash', models.CharField(blank=True, max_length=40)),
                ('comment_count', models.IntegerField(default=0)),
                ('like_count', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True, null=True)),
                ('hidden', models.BooleanField(default=False)),
                ('view_count', models.IntegerField(default=0)),
                ('source', models.FileField(blank=True, max_length=255, null=True, upload_to='%Y/%m/%d')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(blank=True, to='frog.Tag')),
            ],
            options={
                'ordering': ['-created', '-id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ViewRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.CharField(max_length=16)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterModelOptions(
            name='gallery',
            options={'permissions': (('view_gallery', 'Can view gallery'),), 'verbose_name_plural': 'Galleries'},
        ),
        migrations.AddField(
            model_name='gallery',
            name='tags',
            field=models.ManyToManyField(blank=True, to='frog.Tag'),
        ),
        migrations.AddField(
            model_name='image',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='image',
            name='panoramic',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='image',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userpref',
            name='clearance',
            field=models.SmallIntegerField(choices=[(0, 'Public'), (1, 'Private'), (2, 'Personal'), (3, 'Guarded')], default=0),
        ),
        migrations.AddField(
            model_name='video',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='video',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='security',
            field=models.SmallIntegerField(choices=[(0, 'Public'), (1, 'Private'), (2, 'Personal'), (3, 'Guarded')], default=0),
        ),
        migrations.AlterField(
            model_name='image',
            name='custom_thumbnail',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='image',
            name='small',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='image',
            name='source',
            field=models.ImageField(blank=True, height_field='height', max_length=255, null=True, upload_to='%Y/%m/%d', width_field='width'),
        ),
        migrations.AlterField(
            model_name='image',
            name='thumbnail',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='like',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_type_set_for_like', to='contenttypes.ContentType', verbose_name='content_type'),
        ),
        migrations.AlterField(
            model_name='like',
            name='object_pk',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='userpref',
            name='data',
            field=models.TextField(default='{"backgroundColor": "#000000", "tileCount": 9, "emailComments": true, "emailLikes": true, "thumbnailPadding": 0, "semiTransparent": false, "showTags": false, "orderby": "created", "largeThumbnails": false, "slideshowRandomize": true, "slideshowPlayVideo": true, "slideshowDuration": 5}'),
        ),
        migrations.AlterField(
            model_name='video',
            name='custom_thumbnail',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='video',
            name='poster',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='video',
            name='source',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='video',
            name='thumbnail',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_thumbnail',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='videoqueue',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'Queued'), (1, 'Processing'), (2, 'Completed'), (3, 'Error')], default=0),
        ),
        migrations.AddField(
            model_name='gallery',
            name='groups',
            field=models.ManyToManyField(blank=True, to='frog.Group'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='marmosets',
            field=models.ManyToManyField(blank=True, to='frog.Marmoset'),
        ),
        migrations.AlterUniqueTogether(
            name='groupchild',
            unique_together=set([('group', 'content_type', 'object_id')]),
        ),
    ]
