# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-26 05:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('frog', '0013_siteconfig'), ('frog', '0014_auto_20190818_1628'), ('frog', '0015_auto_20190819_2222'), ('frog', '0016_remove_siteconfig_site_url')]

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('frog', '0012_auto_20190606_2210'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Frog', max_length=128)),
                ('favicon', models.FileField(upload_to='')),
                ('icon', models.ImageField(upload_to='')),
                ('link', models.URLField(blank=True, null=True)),
                ('enable_likes', models.BooleanField(default=True)),
                ('default_gallery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='frog.Gallery')),
            ],
        ),
        migrations.RemoveField(
            model_name='image',
            name='small',
        ),
    ]
