# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-18 22:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('frog', '0012_auto_20190606_2210'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Frog', max_length=128)),
                ('favicon', models.FileField(upload_to='')),
                ('icon', models.ImageField(upload_to='')),
                ('link', models.URLField(blank=True, null=True)),
                ('enable_likes', models.BooleanField(default=True)),
                ('default_gallery', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='frog.Gallery')),
                ('query_models', models.ManyToManyField(to='contenttypes.ContentType')),
            ],
        ),
    ]
