# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-09-22 15:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frog', '0013_siteconfig_squashed_0016_remove_siteconfig_site_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfig',
            name='favicon',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
