# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-18 23:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frog', '0013_siteconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='image_size_cap',
            field=models.SmallIntegerField(default=5120),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='site_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='thumbnail_size',
            field=models.SmallIntegerField(default=256),
        ),
    ]
