# Generated by Django 2.2 on 2020-02-13 04:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frog', '0014_auto_20190922_0810'),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='static/')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frog.Tag')),
            ],
        ),
    ]
