# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-23 05:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frog', '0015_auto_20190819_2222'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteconfig',
            name='site_url',
        ),
    ]
